spring:
  application:
    name: itoken-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#springcloud2.1才加的配置
management:
  metrics:
    web:
      server:
        auto-time-requests: false
